# Generated by Django 5.0.1 on 2025-11-05 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Challenge description (supports HTML)"
                    ),
                ),
                ("input_format", models.TextField(blank=True)),
                ("output_format", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                ("sample_input", models.TextField(blank=True, null=True)),
                ("sample_output", models.TextField(blank=True, null=True)),
                (
                    "time_complexity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "space_complexity",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("arrays", "Arrays"),
                            ("strings", "Strings"),
                            ("sorting", "Sorting"),
                            ("searching", "Searching"),
                            ("dynamic_programming", "Dynamic Programming"),
                            ("greedy", "Greedy"),
                            ("graphs", "Graph Theory"),
                            ("trees", "Trees"),
                            ("linked_lists", "Linked Lists"),
                            ("stacks_queues", "Stacks and Queues"),
                            ("recursion", "Recursion"),
                            ("bit_manipulation", "Bit Manipulation"),
                            ("maths", "Mathematics"),
                            ("implementation", "Implementation"),
                            ("data_structures", "Data Structures"),
                            ("number_theory", "Number Theory"),
                            ("hash_map", "Hash Map"),
                            ("matrix", "Matrix"),
                            ("stack", "Stack"),
                            ("queue", "Queue"),
                            ("heap", "Heap"),
                            ("binary_search", "Binary Search"),
                            ("sliding_window", "Sliding Window"),
                            ("basic", "Basic"),
                        ],
                        default="implementation",
                        max_length=50,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.IntegerField(default=10, help_text="Time limit in seconds"),
                ),
                (
                    "memory_limit_mb",
                    models.IntegerField(default=256, help_text="Memory limit in MB"),
                ),
                (
                    "success_rate",
                    models.FloatField(
                        default=0.0, help_text="Percentage of successful submissions"
                    ),
                ),
                ("total_submissions", models.PositiveIntegerField(default=0)),
                ("accepted_submissions", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Coding Challenge",
                "verbose_name_plural": "Coding Challenges",
                "db_table": "coding_api_challenge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField()),
                ("expected_output", models.TextField()),
                ("is_sample", models.BooleanField(default=False)),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this test case is hidden from users and used only for grading.",
                    ),
                ),
                (
                    "score_weight",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="coding.challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Case",
                "verbose_name_plural": "Test Cases",
                "db_table": "coding_api_testcase",
                "ordering": ["-is_sample", "-hidden", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StarterCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("c_cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                        ],
                        help_text="Programming language for this starter code",
                        max_length=50,
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        blank=True,
                        help_text="The initial code snippet provided to the user, e.g., function signature, imports.",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starter_codes",
                        to="coding.challenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Starter Code",
                "verbose_name_plural": "Starter Codes",
                "db_table": "coding_api_startercode",
                "ordering": ["language"],
                "unique_together": {("challenge", "language")},
            },
        ),
    ]
