# Generated by Django 5.0.1 on 2025-11-19 10:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('passing_score', models.PositiveIntegerField(help_text='Percentage score required to pass (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Time limit for completing the certification in minutes')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum number of attempts allowed per user')),
                ('is_active', models.BooleanField(default=True, help_text='Only active certifications are visible to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='courses.course')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Final score as percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_issued_at', models.DateTimeField(blank=True, null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='course_cert.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification Attempt',
                'verbose_name_plural': 'Certification Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('is_multiple_correct', models.BooleanField(default=False, help_text='True if multiple options can be correct')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Weight/points for this question')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in the certification')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are not shown to students')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course_cert.certification')),
            ],
            options={
                'verbose_name': 'Certification Question',
                'verbose_name_plural': 'Certification Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CertificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark as correct answer')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course_cert.certificationquestion')),
            ],
            options={
                'verbose_name': 'Certification Option',
                'verbose_name_plural': 'Certification Options',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(help_text='List of selected option IDs')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='course_cert.certificationattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='course_cert.certificationquestion')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
            },
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['course', 'is_active'], name='course_cert_course__8f8dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationattempt',
            index=models.Index(fields=['user', 'certification'], name='course_cert_user_id_3beaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='certificationattempt',
            index=models.Index(fields=['completed_at'], name='course_cert_complet_22d228_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificationattempt',
            constraint=models.UniqueConstraint(fields=('certification', 'user', 'attempt_number'), name='unique_attempt_number'),
        ),
        migrations.AddConstraint(
            model_name='certificationquestion',
            constraint=models.UniqueConstraint(fields=('certification', 'order'), name='unique_order_per_certification'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_question'),
        ),
    ]
