# Generated by Django 5.0.1 on 2026-01-27 04:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_cert', '0001_initial'),
        ('courses', '0004_taskmcqset_taskmcqsetquestion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='The prompt sent to the AI')),
                ('topic', models.CharField(help_text='Topic for question generation', max_length=200)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('num_questions', models.PositiveIntegerField(default=5, help_text='Number of questions requested')),
                ('model_used', models.CharField(help_text='AI model used for generation', max_length=100)),
                ('provider', models.CharField(default='OPENROUTER', help_text='AI provider used (OpenRouter, Gemini, Z.AI)', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('response_raw', models.TextField(blank=True, help_text='Raw response from the AI', null=True)),
                ('questions_created', models.PositiveIntegerField(default=0, help_text='Number of questions successfully created')),
                ('error_message', models.TextField(blank=True, help_text='Error message if generation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'db_table': 'ai_generation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPENROUTER', 'OpenRouter'), ('GEMINI', 'Google Gemini'), ('ZAI', 'Z.AI')], help_text='AI provider name', max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API key for the provider (stored securely)', max_length=500, null=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='Custom API endpoint (optional)', max_length=500, null=True)),
                ('default_model', models.CharField(blank=True, help_text='Default model to use for this provider', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether this provider is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default provider for AI generation')),
                ('max_tokens', models.PositiveIntegerField(default=4000, help_text='Maximum tokens for API requests')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for AI generation (0.0-2.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('additional_settings', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Provider Settings',
                'verbose_name_plural': 'AI Provider Settings',
                'db_table': 'ai_provider_settings',
                'ordering': ['provider', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationQuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Weight/points for this question in this certification')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order in the certification')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are not shown to students')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='course_cert.certification')),
            ],
            options={
                'verbose_name': 'Certification Question Bank Link',
                'verbose_name_plural': 'Certification Question Bank Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswerBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(help_text='List of selected option IDs from QuestionBankOption')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_answers', to='course_cert.certificationattempt')),
                ('cert_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='course_cert.certificationquestionbank')),
            ],
            options={
                'verbose_name': 'Attempt Answer (Bank)',
                'verbose_name_plural': 'Attempt Answers (Bank)',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('explanation', models.TextField(blank=True, help_text='Optional explanation for the correct answer', null=True)),
                ('is_multiple_correct', models.BooleanField(default=False, help_text='True if multiple options can be correct')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', help_text='Difficulty level of the question', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Tags for filtering questions (e.g., ['python', 'loops', 'basics'])")),
                ('source', models.CharField(choices=[('MANUAL', 'Manually Created'), ('AI_GENERATED', 'AI Generated'), ('IMPORTED', 'Imported')], default='MANUAL', help_text='How this question was created', max_length=20)),
                ('ai_prompt', models.TextField(blank=True, help_text='The prompt used to generate this question (if AI generated)', null=True)),
                ('ai_model', models.CharField(blank=True, help_text='The AI model used to generate this question', max_length=100, null=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Default weight/points for this question (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are not available for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: Link question to a specific course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question Bank Item',
                'verbose_name_plural': 'Question Bank Items',
                'db_table': 'question_bank',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificationquestionbank',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_certifications', to='course_cert.questionbank'),
        ),
        migrations.CreateModel(
            name='QuestionBankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: Link category to a specific course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_categories', to='courses.course')),
            ],
            options={
                'verbose_name': 'Question Bank Category',
                'verbose_name_plural': 'Question Bank Categories',
                'db_table': 'question_bank_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='questionbank',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for organizing questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='course_cert.questionbankcategory'),
        ),
        migrations.CreateModel(
            name='QuestionBankOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False, help_text='Mark as correct answer')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the option')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course_cert.questionbank')),
            ],
            options={
                'verbose_name': 'Question Bank Option',
                'verbose_name_plural': 'Question Bank Options',
                'db_table': 'question_bank_options',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='attemptanswerbank',
            constraint=models.UniqueConstraint(fields=('attempt', 'cert_question'), name='unique_bank_answer_per_question'),
        ),
        migrations.AddConstraint(
            model_name='certificationquestionbank',
            constraint=models.UniqueConstraint(fields=('certification', 'question'), name='unique_question_per_certification'),
        ),
        migrations.AddConstraint(
            model_name='certificationquestionbank',
            constraint=models.UniqueConstraint(fields=('certification', 'order'), name='unique_order_per_certification_bank'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['difficulty', 'is_active'], name='question_ba_difficu_7e4199_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['category', 'is_active'], name='question_ba_categor_cc743e_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['source', 'is_active'], name='question_ba_source_35e491_idx'),
        ),
    ]
