# Generated by Django 5.0.1 on 2026-02-14 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0007_college_signature"),
        ("courses", "0020_taskmcqset_taskmcqsetquestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProctoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("terminated", "Terminated (Violation)"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_frames", models.PositiveIntegerField(default=0)),
                ("face_present_frames", models.PositiveIntegerField(default=0)),
                ("face_absent_frames", models.PositiveIntegerField(default=0)),
                ("multiple_face_frames", models.PositiveIntegerField(default=0)),
                ("look_away_frames", models.PositiveIntegerField(default=0)),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("violation_count", models.PositiveIntegerField(default=0)),
                ("high_severity_count", models.PositiveIntegerField(default=0)),
                ("medium_severity_count", models.PositiveIntegerField(default=0)),
                ("low_severity_count", models.PositiveIntegerField(default=0)),
                ("session_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_sessions",
                        to="courses.task",
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ProctoringFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_number", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField()),
                ("faces_detected", models.PositiveIntegerField(default=0)),
                ("face_bbox", models.JSONField(blank=True, default=dict)),
                ("looking_at_screen", models.BooleanField(default=True)),
                ("gaze_direction", models.CharField(default="center", max_length=20)),
                ("suspicious_objects", models.JSONField(blank=True, default=list)),
                (
                    "frame_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="proctoring_frames/"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="proctoring.proctoringsession",
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_frames",
                "ordering": ["frame_number"],
            },
        ),
        migrations.CreateModel(
            name="ProctoringSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("face_detection_enabled", models.BooleanField(default=True)),
                ("gaze_detection_enabled", models.BooleanField(default=True)),
                ("object_detection_enabled", models.BooleanField(default=False)),
                ("face_verification_enabled", models.BooleanField(default=False)),
                (
                    "max_absent_frames",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Max consecutive frames without face before violation",
                    ),
                ),
                (
                    "max_multiple_face_frames",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Max consecutive frames with multiple faces before violation",
                    ),
                ),
                (
                    "max_look_away_frames",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Max consecutive frames looking away before violation",
                    ),
                ),
                (
                    "min_face_confidence",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                (
                    "min_object_confidence",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
                ),
                (
                    "face_similarity_threshold",
                    models.DecimalField(decimal_places=2, default=0.6, max_digits=3),
                ),
                (
                    "auto_terminate_on_high_severity",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically terminate quiz on high severity violation",
                    ),
                ),
                (
                    "auto_terminate_threshold",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of high severity violations before auto-terminate",
                    ),
                ),
                ("capture_screenshots", models.BooleanField(default=True)),
                ("capture_interval_frames", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_settings",
                        to="api.college",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proctoring_settings",
                        to="courses.task",
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_settings",
            },
        ),
        migrations.CreateModel(
            name="ProctoringViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "violation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("face_not_detected", "Face Not Detected"),
                            ("multiple_faces_detected", "Multiple Faces Detected"),
                            ("prolonged_look_away", "Prolonged Look Away"),
                            ("suspicious_gaze_pattern", "Suspicious Gaze Pattern"),
                            (
                                "suspicious_object_detected",
                                "Suspicious Object Detected",
                            ),
                            ("face_mismatch", "Face Mismatch (Different Person)"),
                            ("tab_switch", "Tab/Window Switch"),
                            ("fullscreen_exit", "Fullscreen Exit"),
                            ("copy_paste_attempt", "Copy/Paste Attempt"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("frame_number", models.PositiveIntegerField(default=0)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        help_text="Screenshot at time of violation",
                        null=True,
                        upload_to="proctoring_evidence/",
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True, null=True)),
                ("is_false_positive", models.BooleanField(default=False)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="violations",
                        to="proctoring.proctoringsession",
                    ),
                ),
            ],
            options={
                "db_table": "proctoring_violations",
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="proctoringsession",
            index=models.Index(
                fields=["student", "task"], name="proctoring__student_ea29de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctoringsession",
            index=models.Index(fields=["status"], name="proctoring__status_ba9e3e_idx"),
        ),
        migrations.AddIndex(
            model_name="proctoringsession",
            index=models.Index(
                fields=["risk_score"], name="proctoring__risk_sc_aada7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctoringframe",
            index=models.Index(
                fields=["session", "frame_number"],
                name="proctoring__session_defab0_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="proctoringframe",
            unique_together={("session", "frame_number")},
        ),
        migrations.AddIndex(
            model_name="proctoringviolation",
            index=models.Index(
                fields=["session", "timestamp"], name="proctoring__session_4e65dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctoringviolation",
            index=models.Index(
                fields=["violation_type"], name="proctoring__violati_a7cc32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctoringviolation",
            index=models.Index(
                fields=["severity"], name="proctoring__severit_b84c0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proctoringviolation",
            index=models.Index(
                fields=["reviewed"], name="proctoring__reviewe_b4d7e3_idx"
            ),
        ),
    ]
