FROM python:3.11-slim-bullseye

WORKDIR /code

RUN apt-get update && apt-get install -y \
    build-essential \
    openjdk-11-jdk \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]
