# Generated by Django 5.0.1 on 2025-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='signature',
            field=models.ImageField(blank=True, help_text='College signature image', null=True, upload_to='college_signatures/'),
        ),
    ]
