# Generated by Django 5.0.1 on 2025-11-19 10:59

import courses.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Course ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration_hours', models.IntegerField(default=0, help_text='Estimated course duration in hours')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/')),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='course_intro_videos/', verbose_name='Introduction Video')),
                ('video_intro_url', models.URLField(blank=True, help_text='Introduction video URL (YouTube, Vimeo, etc.)', null=True)),
                ('current_enrollments', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(blank=True, help_text='College that owns this course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.college')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within course')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Syllabi',
                'db_table': 'syllabi',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project'), ('exercise', 'Exercise'), ('exam', 'Exam')], default='assignment', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='task_resources/')),
                ('reference_links', models.JSONField(blank=True, default=list, help_text='Array of reference URLs')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Time limit in minutes')),
                ('max_score', models.IntegerField(default=100)),
                ('passing_score', models.IntegerField(default=60)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['order', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(upload_to='task_documents/', verbose_name='Document File')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within task', verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.task')),
            ],
            options={
                'db_table': 'task_documents',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('coding', 'Coding Question')], default='mcq', max_length=10)),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('marks', models.PositiveIntegerField(default=1, help_text='Marks for this question')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within task', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.task')),
            ],
            options={
                'db_table': 'task_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_1_text', models.CharField(max_length=500, verbose_name='Choice 1')),
                ('choice_1_is_correct', models.BooleanField(default=False, verbose_name='Choice 1 Correct')),
                ('choice_2_text', models.CharField(max_length=500, verbose_name='Choice 2')),
                ('choice_2_is_correct', models.BooleanField(default=False, verbose_name='Choice 2 Correct')),
                ('choice_3_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Choice 3')),
                ('choice_3_is_correct', models.BooleanField(default=False, verbose_name='Choice 3 Correct')),
                ('choice_4_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Choice 4')),
                ('choice_4_is_correct', models.BooleanField(default=False, verbose_name='Choice 4 Correct')),
                ('solution_explanation', models.TextField(help_text='Explanation for the correct answer', verbose_name='Solution Explanation')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_details', to='courses.taskquestion')),
            ],
            options={
                'verbose_name': 'MCQ Details',
                'verbose_name_plural': 'MCQ Details',
                'db_table': 'task_mcq_details',
            },
        ),
        migrations.CreateModel(
            name='TaskCoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(help_text='Full description of the coding problem', verbose_name='Problem Description')),
                ('input_description', models.TextField(help_text='Describes the format of input data', verbose_name='Input Description')),
                ('sample_input', models.TextField(help_text="Example input for testing (e.g., '5 3')", verbose_name='Sample Input')),
                ('output_description', models.TextField(help_text='Describes the format/structure of expected output', verbose_name='Output Format Description')),
                ('sample_output', models.TextField(help_text='Expected output for the sample input', verbose_name='Sample Output')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('javascript', 'JavaScript'), ('csharp', 'C#'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('php', 'PHP'), ('typescript', 'TypeScript'), ('kotlin', 'Kotlin'), ('swift', 'Swift')], default='python', help_text='Required programming language', max_length=20)),
                ('constraints', models.TextField(blank=True, help_text='Problem constraints (time/space complexity, input limits)', null=True)),
                ('hints', models.TextField(blank=True, help_text='Hints to help solve the problem', null=True)),
                ('starter_code', models.TextField(blank=True, help_text='Pre-written starter code for students to begin with', null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_details', to='courses.taskquestion')),
            ],
            options={
                'verbose_name': 'Coding Question Details',
                'verbose_name_plural': 'Coding Question Details',
                'db_table': 'task_coding_details',
            },
        ),
        migrations.CreateModel(
            name='TaskRichTextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text='URL-friendly title', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within task', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtext_pages', to='courses.task')),
            ],
            options={
                'db_table': 'task_richtext_pages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('cpp', 'C++'), ('c', 'C'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('bash', 'Bash'), ('json', 'JSON')], default='python', max_length=50)),
                ('code', models.TextField(verbose_name='Code Content')),
                ('title', models.CharField(blank=True, help_text='Optional code block title', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_blocks', to='courses.taskrichtextpage')),
            ],
            options={
                'db_table': 'task_code_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('submission_links', models.JSONField(blank=True, default=list)),
                ('completed_content', models.JSONField(blank=True, default=dict, help_text='Tracks completed content items: {content_type: [content_ids]}')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('returned', 'Returned for Revision'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.task')),
            ],
            options={
                'db_table': 'task_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input data for this test case', verbose_name='Input Data')),
                ('expected_output', models.TextField(help_text='Expected output for this input', verbose_name='Expected Output')),
                ('is_sample', models.BooleanField(default=False, help_text='If true, this test case is visible to students')),
                ('hidden', models.BooleanField(default=False, help_text='If true, this test case is hidden during grading')),
                ('score_weight', models.PositiveIntegerField(default=1, help_text='Weight/points for this test case')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coding_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='courses.taskcoding')),
            ],
            options={
                'db_table': 'task_test_cases',
                'ordering': ['-is_sample', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Text Content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='courses.taskrichtextpage')),
            ],
            options={
                'db_table': 'task_text_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='task_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm'])], verbose_name='Video File')),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True, validators=[courses.models.validate_youtube_url], verbose_name='YouTube URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within task', verbose_name='Order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.task')),
            ],
            options={
                'db_table': 'task_videos',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskVideoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Video Title')),
                ('youtube_url', models.URLField(help_text='YouTube video URL', max_length=500, verbose_name='YouTube URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Video Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_blocks', to='courses.taskrichtextpage')),
            ],
            options={
                'db_table': 'task_video_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_preview', models.BooleanField(default=False, help_text='Available before enrollment')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course', verbose_name='Associated Course')),
            ],
            options={
                'db_table': 'topics',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.topic'),
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of topic in syllabus')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.syllabus')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
            options={
                'db_table': 'syllabus_topics',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='syllabus',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='syllabi', through='courses.SyllabusTopic', to='courses.topic'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='courses_slug_360be0_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status', 'is_featured'], name='courses_status_9c57da_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['college'], name='courses_college_40ce39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='taskdocument',
            index=models.Index(fields=['task', 'order'], name='task_docume_task_id_37ae96_idx'),
        ),
        migrations.AddIndex(
            model_name='taskquestion',
            index=models.Index(fields=['task', 'order'], name='task_questi_task_id_b94aac_idx'),
        ),
        migrations.AddIndex(
            model_name='taskquestion',
            index=models.Index(fields=['question_type'], name='task_questi_questio_2bf1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrichtextpage',
            index=models.Index(fields=['task', 'order'], name='task_richte_task_id_7c7549_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrichtextpage',
            index=models.Index(fields=['slug'], name='task_richte_slug_54542f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskrichtextpage',
            unique_together={('task', 'slug')},
        ),
        migrations.AddIndex(
            model_name='taskcodeblock',
            index=models.Index(fields=['page', 'order'], name='task_code_b_page_id_478633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasksubmission',
            unique_together={('task', 'student')},
        ),
        migrations.AddIndex(
            model_name='tasktestcase',
            index=models.Index(fields=['coding_question', 'is_sample'], name='task_test_c_coding__14aa3d_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktextblock',
            index=models.Index(fields=['page', 'order'], name='task_text_b_page_id_8f9dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='taskvideo',
            index=models.Index(fields=['task', 'order'], name='task_videos_task_id_4c4f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskvideoblock',
            index=models.Index(fields=['page', 'order'], name='task_video__page_id_cdc2d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syllabustopic',
            unique_together={('syllabus', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('course', 'order')},
        ),
    ]
