# Generated by Django 5.0.1 on 2025-11-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='task',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_type',
        ),
    ]
