# Generated by Django 5.0.1 on 2025-12-10 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_task_description_remove_task_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHighlightBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content will be displayed exactly as entered with preserved formatting', verbose_name='Highlight Content')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_blocks', to='courses.taskrichtextpage')),
            ],
            options={
                'db_table': 'task_highlight_blocks',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['page', 'order'], name='task_highli_page_id_5228be_idx')],
            },
        ),
    ]
