# Generated by Django 5.0.1 on 2026-01-14 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_taskhighlightblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMCQSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_set_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text="e.g., 'Java Basics - Test 1'", max_length=255, verbose_name='MCQ Set Title')),
                ('description', models.TextField(blank=True, help_text='Optional description for this MCQ set', null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within task', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_sets', to='courses.task')),
            ],
            options={
                'db_table': 'task_mcq_sets',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskMCQSetQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question Text')),
                ('marks', models.PositiveIntegerField(default=1, help_text='Marks for this question')),
                ('choice_1_text', models.CharField(max_length=500, verbose_name='Choice 1')),
                ('choice_1_is_correct', models.BooleanField(default=False, verbose_name='Choice 1 Correct')),
                ('choice_2_text', models.CharField(max_length=500, verbose_name='Choice 2')),
                ('choice_2_is_correct', models.BooleanField(default=False, verbose_name='Choice 2 Correct')),
                ('choice_3_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Choice 3')),
                ('choice_3_is_correct', models.BooleanField(default=False, verbose_name='Choice 3 Correct')),
                ('choice_4_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Choice 4')),
                ('choice_4_is_correct', models.BooleanField(default=False, verbose_name='Choice 4 Correct')),
                ('solution_explanation', models.TextField(help_text='Explanation for the correct answer', verbose_name='Solution Explanation')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within MCQ set', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mcq_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='courses.taskmcqset')),
            ],
            options={
                'db_table': 'task_mcq_set_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taskmcqset',
            index=models.Index(fields=['task', 'order'], name='task_mcq_se_task_id_efc5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='taskmcqsetquestion',
            index=models.Index(fields=['mcq_set', 'order'], name='task_mcq_se_mcq_set_9d6d39_idx'),
        ),
    ]
