# Generated by Django 5.0.1 on 2025-11-19 10:59

import company.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('coding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/', verbose_name='Company Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('hiring_period_start', models.DateField(blank=True, null=True, verbose_name='Hiring Period Start')),
                ('hiring_period_end', models.DateField(blank=True, null=True, verbose_name='Hiring Period End')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Company Website')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Location')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Industry')),
                ('employee_count', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee Count')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_hiring', models.BooleanField(default=False, verbose_name='Currently Hiring')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.college', verbose_name='Added by College')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Concept Name')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Concept Description')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=60, help_text='Estimated time to complete all challenges in this concept', verbose_name='Estimated Time (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='company.company')),
            ],
            options={
                'verbose_name': 'Concept',
                'verbose_name_plural': 'Concepts',
                'db_table': 'concepts',
                'ordering': ['company', 'order', 'name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(verbose_name='Job Description')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract'), ('FREELANCE', 'Freelance')], default='FULL_TIME', max_length=20, verbose_name='Job Type')),
                ('experience_level', models.CharField(choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead/Manager')], default='ENTRY', max_length=20, verbose_name='Experience Level')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Location')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('salary_currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated list', null=True, verbose_name='Required Skills')),
                ('qualifications', models.TextField(blank=True, null=True, verbose_name='Qualifications')),
                ('responsibilities', models.TextField(blank=True, null=True, verbose_name='Responsibilities')),
                ('application_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Application Deadline')),
                ('application_url', models.URLField(blank=True, null=True, verbose_name='Application URL')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='ConceptChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order in Concept')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('weight', models.FloatField(default=1.0, help_text='Multiplier for challenge score in this concept', verbose_name='Score Weight')),
                ('custom_time_limit', models.PositiveIntegerField(blank=True, help_text='Override default challenge time limit for this concept', null=True, verbose_name='Custom Time Limit (seconds)')),
                ('hint_video_file', models.FileField(blank=True, help_text='Upload a video file as hint (mp4, mov, avi, mkv)', null=True, upload_to='company_challenge_hints/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv'])], verbose_name='Hint Video File')),
                ('hint_youtube_url', models.URLField(blank=True, help_text='Enter a YouTube video URL as hint', max_length=500, null=True, validators=[company.models.validate_youtube_url], verbose_name='Hint YouTube URL')),
                ('hint_video_title', models.CharField(blank=True, help_text='Title for the hint video', max_length=255, null=True, verbose_name='Hint Video Title')),
                ('hint_video_description', models.TextField(blank=True, help_text='Description for the hint video', null=True, verbose_name='Hint Video Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_links', to='coding.challenge')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='company.concept')),
            ],
            options={
                'verbose_name': 'Concept Challenge',
                'verbose_name_plural': 'Concept Challenges',
                'db_table': 'concept_challenges',
                'ordering': ['concept', 'order', 'challenge__title'],
                'unique_together': {('concept', 'challenge')},
            },
        ),
    ]
