# Generated by Django 5.0.1 on 2025-11-05 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coding", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(help_text="Emoji or icon class", max_length=50),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("MILESTONE", "Milestone"),
                            ("STREAK", "Streak"),
                            ("CHALLENGE", "Challenge"),
                            ("PERFORMANCE", "Performance"),
                            ("SPECIAL", "Special"),
                        ],
                        default="MILESTONE",
                        max_length=20,
                    ),
                ),
                (
                    "points_required",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "challenges_required",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "streak_required",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("COMMON", "Common"),
                            ("RARE", "Rare"),
                            ("EPIC", "Epic"),
                            ("LEGENDARY", "Legendary"),
                        ],
                        default="COMMON",
                        max_length=20,
                    ),
                ),
                (
                    "bonus_points",
                    models.IntegerField(
                        default=0,
                        help_text="Bonus points awarded when earning this badge",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "badges",
                "ordering": ["rarity", "name"],
            },
        ),
        migrations.CreateModel(
            name="CodingChallengeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("c_cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("WRONG_ANSWER", "Wrong Answer"),
                            ("RUNTIME_ERROR", "Runtime Error"),
                            ("TIME_LIMIT_EXCEEDED", "Time Limit Exceeded"),
                            ("COMPILATION_ERROR", "Compilation Error"),
                            ("MEMORY_LIMIT_EXCEEDED", "Memory Limit Exceeded"),
                            ("SYSTEM_ERROR", "System Error"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("passed_tests", models.IntegerField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "runtime",
                    models.FloatField(default=0.0, help_text="Runtime in milliseconds"),
                ),
                (
                    "memory_used",
                    models.FloatField(default=0.0, help_text="Memory used in KB"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed test case results"
                    ),
                ),
                ("compilation_message", models.TextField(blank=True)),
                (
                    "is_best_submission",
                    models.BooleanField(
                        default=False,
                        help_text="User's best submission for this challenge",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to="coding.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coding_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coding Challenge Submission",
                "verbose_name_plural": "Coding Challenge Submissions",
                "db_table": "student_coding_challenge_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentChallengeSubmission",
            fields=[],
            options={
                "verbose_name": "Student Challenge Submission (Legacy)",
                "verbose_name_plural": "Student Challenge Submissions (Legacy)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("student.codingchallengesubmission",),
        ),
        migrations.CreateModel(
            name="CompanyChallengeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_id",
                    models.IntegerField(
                        help_text="Company ID from company_challenges system"
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "concept_id",
                    models.IntegerField(
                        help_text="Concept ID from company_challenges system"
                    ),
                ),
                ("concept_name", models.CharField(blank=True, max_length=255)),
                (
                    "challenge_id",
                    models.IntegerField(
                        help_text="Challenge ID from coding_challenges system"
                    ),
                ),
                (
                    "challenge_slug",
                    models.SlugField(help_text="Challenge slug for reference"),
                ),
                ("challenge_title", models.CharField(blank=True, max_length=255)),
                ("submitted_code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("c_cpp", "C++"),
                            ("c", "C"),
                            ("javascript", "JavaScript"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("WRONG_ANSWER", "Wrong Answer"),
                            ("RUNTIME_ERROR", "Runtime Error"),
                            ("TIME_LIMIT_EXCEEDED", "Time Limit Exceeded"),
                            ("COMPILATION_ERROR", "Compilation Error"),
                            ("MEMORY_LIMIT_EXCEEDED", "Memory Limit Exceeded"),
                            ("SYSTEM_ERROR", "System Error"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("passed_tests", models.IntegerField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                (
                    "runtime",
                    models.FloatField(default=0.0, help_text="Runtime in milliseconds"),
                ),
                (
                    "memory_used",
                    models.FloatField(default=0.0, help_text="Memory used in KB"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="Detailed test case results"
                    ),
                ),
                ("compilation_message", models.TextField(blank=True)),
                (
                    "is_best_submission",
                    models.BooleanField(
                        default=False,
                        help_text="User's best submission for this challenge in this company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_challenge_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Challenge Submission",
                "verbose_name_plural": "Company Challenge Submissions",
                "db_table": "student_company_challenge_submission",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("document", "Document"),
                            ("question", "Question"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_id",
                    models.IntegerField(help_text="ID of the video/document/question"),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_content_progress",
                        to="courses.course",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_content_progress",
                        to="courses.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Progress",
                "verbose_name_plural": "Content Progress",
                "db_table": "student_content_progress",
            },
        ),
        migrations.CreateModel(
            name="ContentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("question", "Question Submission"),
                            ("document", "Document Completion"),
                            ("video", "Video Completion"),
                            ("page", "Page Completion"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mcq_selected_choice",
                    models.IntegerField(
                        blank=True,
                        help_text="Selected choice number (1-4) for MCQ",
                        null=True,
                    ),
                ),
                (
                    "code_submitted",
                    models.TextField(
                        blank=True,
                        help_text="Submitted code for coding questions",
                        null=True,
                    ),
                ),
                (
                    "answer_text",
                    models.TextField(
                        blank=True, help_text="Text answer or notes", null=True
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="For MCQ: indicates correctness",
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Points earned",
                        max_digits=5,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Marks content as completed"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.taskdocument",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.taskrichtextpage",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.taskquestion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_submissions",
                        to="courses.task",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.taskvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Submission",
                "verbose_name_plural": "Content Submissions",
                "db_table": "content_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leaderboard_type",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("COLLEGE", "College"),
                            ("COURSE", "Course"),
                            ("COMPANY", "Company"),
                        ],
                        default="GLOBAL",
                        max_length=20,
                    ),
                ),
                (
                    "time_period",
                    models.CharField(
                        choices=[
                            ("ALL_TIME", "All Time"),
                            ("MONTHLY", "Monthly"),
                            ("WEEKLY", "Weekly"),
                            ("DAILY", "Daily"),
                        ],
                        default="ALL_TIME",
                        max_length=20,
                    ),
                ),
                ("rank", models.IntegerField()),
                ("total_points", models.IntegerField()),
                ("challenges_solved", models.IntegerField()),
                ("badge_count", models.IntegerField(default=0)),
                ("college_id", models.IntegerField(blank=True, null=True)),
                (
                    "course_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_slug",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leaderboard_cache",
                "ordering": ["leaderboard_type", "time_period", "rank"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION", "Code Submission"),
                            ("CHALLENGE_SOLVED", "Challenge Solved"),
                            ("COURSE_START", "Course Started"),
                            ("COURSE_COMPLETE", "Course Completed"),
                            ("BADGE_EARNED", "Badge Earned"),
                            ("LOGIN", "Login"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activity_date", models.DateField(default=django.utils.timezone.now)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("points_earned", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="student.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_badges",
                "ordering": ["-earned_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.IntegerField(default=0, help_text="Total points earned"),
                ),
                (
                    "global_rank",
                    models.IntegerField(
                        blank=True, help_text="Global ranking position", null=True
                    ),
                ),
                (
                    "college_rank",
                    models.IntegerField(
                        blank=True, help_text="College-wise ranking position", null=True
                    ),
                ),
                (
                    "challenges_solved",
                    models.IntegerField(default=0, help_text="Total challenges solved"),
                ),
                (
                    "easy_solved",
                    models.IntegerField(default=0, help_text="Easy challenges solved"),
                ),
                (
                    "medium_solved",
                    models.IntegerField(
                        default=0, help_text="Medium challenges solved"
                    ),
                ),
                (
                    "hard_solved",
                    models.IntegerField(default=0, help_text="Hard challenges solved"),
                ),
                (
                    "company_challenges_solved",
                    models.IntegerField(
                        default=0, help_text="Company challenges solved"
                    ),
                ),
                (
                    "current_streak",
                    models.IntegerField(
                        default=0, help_text="Current daily solving streak"
                    ),
                ),
                (
                    "longest_streak",
                    models.IntegerField(default=0, help_text="Longest streak achieved"),
                ),
                (
                    "last_activity",
                    models.DateField(
                        blank=True, help_text="Last submission date", null=True
                    ),
                ),
                (
                    "total_submissions",
                    models.IntegerField(default=0, help_text="Total submissions made"),
                ),
                (
                    "successful_submissions",
                    models.IntegerField(default=0, help_text="Successful submissions"),
                ),
                (
                    "total_time_spent_minutes",
                    models.IntegerField(default=0, help_text="Total time spent coding"),
                ),
                (
                    "average_runtime_ms",
                    models.FloatField(
                        default=0.0,
                        help_text="Average runtime of successful submissions",
                    ),
                ),
                (
                    "average_memory_kb",
                    models.FloatField(default=0.0, help_text="Average memory usage"),
                ),
                ("courses_enrolled", models.IntegerField(default=0)),
                ("courses_completed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["-total_points", "global_rank"],
            },
        ),
        migrations.AddIndex(
            model_name="codingchallengesubmission",
            index=models.Index(
                fields=["user", "challenge"], name="student_cod_user_id_2f9791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallengesubmission",
            index=models.Index(
                fields=["challenge", "status"], name="student_cod_challen_d4d081_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codingchallengesubmission",
            index=models.Index(
                fields=["submitted_at"], name="student_cod_submitt_e99581_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companychallengesubmission",
            index=models.Index(
                fields=["user", "company_id", "challenge_id"],
                name="student_com_user_id_1b1ae0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companychallengesubmission",
            index=models.Index(
                fields=["challenge_id", "status"], name="student_com_challen_33f5fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companychallengesubmission",
            index=models.Index(
                fields=["submitted_at"], name="student_com_submitt_e2a04a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprogress",
            index=models.Index(
                fields=["user", "course"], name="student_con_user_id_fc1be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprogress",
            index=models.Index(
                fields=["user", "task"], name="student_con_user_id_04b28f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentprogress",
            index=models.Index(
                fields=["is_completed"], name="student_con_is_comp_37271d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contentprogress",
            unique_together={("user", "content_type", "content_id")},
        ),
        migrations.AddIndex(
            model_name="contentsubmission",
            index=models.Index(
                fields=["student", "task"], name="content_sub_student_419586_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentsubmission",
            index=models.Index(
                fields=["submission_type"], name="content_sub_submiss_0657a5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("question__isnull", False)),
                fields=("student", "question"),
                name="unique_student_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("document__isnull", False)),
                fields=("student", "document"),
                name="unique_student_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video__isnull", False)),
                fields=("student", "video"),
                name="unique_student_video",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("page__isnull", False)),
                fields=("student", "page"),
                name="unique_student_page",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardcache",
            index=models.Index(
                fields=["leaderboard_type", "time_period", "rank"],
                name="leaderboard_leaderb_61f569_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardcache",
            index=models.Index(
                fields=["user", "leaderboard_type"],
                name="leaderboard_user_id_85d04e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "activity_date"], name="user_activi_user_id_0a4107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type"], name="user_activi_activit_534635_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge")},
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["global_rank"], name="user_profil_global__daf465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["college_rank"], name="user_profil_college_9eb802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["total_points"], name="user_profil_total_p_7e9068_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["-total_points"], name="user_profil_total_p_f42f97_idx"
            ),
        ),
    ]
