# Generated by Django 5.0.1 on 2026-01-14 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_taskmcqset_taskmcqsetquestion_and_more'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentsubmission',
            name='mcq_set_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.taskmcqsetquestion'),
        ),
        migrations.AddConstraint(
            model_name='contentsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('mcq_set_question__isnull', False)), fields=('student', 'mcq_set_question'), name='unique_student_mcq_set_question'),
        ),
    ]
